//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolejka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kolejka()
        {
            this.Mecz = new HashSet<Mecz>();
        }
    
        public int ID_KOLEJKA { get; set; }
        public Nullable<int> ID_LIGA { get; set; }
        public string SEZON { get; set; }
        public string NUMER { get; set; }
        public Nullable<System.DateTime> DATA_KOLEJKI { get; set; }
    
        public virtual Liga Liga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mecz> Mecz { get; set; }
    }
}
