//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mecz()
        {
            this.Zdarzenies = new HashSet<Zdarzenie>();
            this.Sedzia_na_mecz = new HashSet<Sedzia_na_mecz>();
            this.Sklad_na_mecz = new HashSet<Sklad_na_mecz>();
        }
    
        public int ID_MECZ { get; set; }
        public int ID_KLUB { get; set; }
        public Nullable<int> ID_STADIONU { get; set; }
        public Nullable<int> KLU_ID_KLUB { get; set; }
        public Nullable<System.DateTime> DATA_MECZU { get; set; }
        public string MIEJSCOWOSC { get; set; }
    
        public virtual KLUB KLUB { get; set; }
        public virtual KLUB KLUB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdarzenie> Zdarzenies { get; set; }
        public virtual Stadion Stadion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sedzia_na_mecz> Sedzia_na_mecz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_na_mecz> Sklad_na_mecz { get; set; }
    }
}
