//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mecz()
        {
            this.Zdarzenie = new HashSet<Zdarzenie>();
        }
    
        public int ID_MECZ { get; set; }
        public Nullable<int> ID_KOLEJKA { get; set; }
        public Nullable<int> ID_GOSC { get; set; }
        public Nullable<int> ID_GOSPODARZ { get; set; }
        public Nullable<int> ID_STADION { get; set; }
        public Nullable<int> WYNIK_GOSPODARZ { get; set; }
        public Nullable<int> WYNIK_GOSC { get; set; }
    
        public virtual Klub Klub { get; set; }
        public virtual Klub Klub1 { get; set; }
        public virtual Kolejka Kolejka { get; set; }
        public virtual Stadion Stadion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdarzenie> Zdarzenie { get; set; }
    }
}
