
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApInt1
{

using System;
    using System.Collections.Generic;
    
public partial class Rodzaj_pozycji
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Rodzaj_pozycji()
    {

        this.Sklad_na_mecz = new HashSet<Sklad_na_mecz>();

    }


    public int ID_POZYCJI { get; set; }

    public string NAZWA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sklad_na_mecz> Sklad_na_mecz { get; set; }

}

}
