//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RugbyEntities : DbContext
    {
        public RugbyEntities()
            : base("name=RugbyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klub> Klub { get; set; }
        public virtual DbSet<Kolejka> Kolejka { get; set; }
        public virtual DbSet<Liga> Liga { get; set; }
        public virtual DbSet<Mecz> Mecz { get; set; }
        public virtual DbSet<Stadion> Stadion { get; set; }
        public virtual DbSet<Zawodnik> Zawodnik { get; set; }
        public virtual DbSet<Zdarzenie> Zdarzenie { get; set; }
    }
}
