//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RugbyEntities : DbContext
    {
        public RugbyEntities()
            : base("name=RugbyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funkcja_sedziowska> Funkcja_sedziowska { get; set; }
        public virtual DbSet<KLUB> KLUBs { get; set; }
        public virtual DbSet<Mecz> Meczs { get; set; }
        public virtual DbSet<Rodzaj_pozycji> Rodzaj_pozycji { get; set; }
        public virtual DbSet<Sedzia> Sedzias { get; set; }
        public virtual DbSet<Sedzia_na_mecz> Sedzia_na_mecz { get; set; }
        public virtual DbSet<Sezon> Sezons { get; set; }
        public virtual DbSet<Sklad_na_mecz> Sklad_na_mecz { get; set; }
        public virtual DbSet<Stadion> Stadions { get; set; }
        public virtual DbSet<Typ_zdarzenia> Typ_zdarzenia { get; set; }
        public virtual DbSet<Zawodnik> Zawodniks { get; set; }
        public virtual DbSet<Zdarzenie> Zdarzenies { get; set; }
    }
}
