
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApInt1
{

using System;
    using System.Collections.Generic;
    
public partial class Sedzia
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sedzia()
    {

        this.Sedzia_na_mecz = new HashSet<Sedzia_na_mecz>();

    }


    public int ID_OSOBA { get; set; }

    public Nullable<int> WIEK { get; set; }

    public string NAZWISKO { get; set; }

    public string IMIE { get; set; }

    public string KRAJ { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sedzia_na_mecz> Sedzia_na_mecz { get; set; }

}

}
