
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApInt1
{

using System;
    using System.Collections.Generic;
    
public partial class Zawodnik
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Zawodnik()
    {

        this.Sklad_na_mecz = new HashSet<Sklad_na_mecz>();

        this.Zdarzenies = new HashSet<Zdarzenie>();

    }


    public int ID_OSOBA { get; set; }

    public Nullable<int> WIEK { get; set; }

    public string NAZWISKO { get; set; }

    public string IMIE { get; set; }

    public string KRAJ { get; set; }

    public byte[] ZDJECIA { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sklad_na_mecz> Sklad_na_mecz { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zdarzenie> Zdarzenies { get; set; }

}

}
