//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnik
    {
        public int ID_ZAWODNIK { get; set; }
        public Nullable<int> ID_KLUB { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public Nullable<System.DateTime> DATA_URODZENIA { get; set; }
        public string NARODOWOSC { get; set; }
    
        public virtual Klub Klub { get; set; }
    }
}
