//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdarzenie
    {
        public int ID_ZDARZENIA { get; set; }
        public Nullable<int> ID_MECZ { get; set; }
        public int ID_TYPU_ZDARZENIA { get; set; }
        public Nullable<int> ID_OSOBA { get; set; }
        public Nullable<System.TimeSpan> CZAS { get; set; }
    
        public virtual Mecz Mecz { get; set; }
        public virtual Typ_zdarzenia Typ_zdarzenia { get; set; }
        public virtual Zawodnik Zawodnik { get; set; }
    }
}
