//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApInt1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdarzenie
    {
        public int ID_ZDARZENIE { get; set; }
        public Nullable<int> ID_MECZ { get; set; }
        public Nullable<int> ID_KLUB { get; set; }
        public string NAZWA { get; set; }
        public string MINUTA { get; set; }
    
        public virtual Klub Klub { get; set; }
        public virtual Mecz Mecz { get; set; }
    }
}
